add missing object file to makefile
wcs/fileutil.c was not being compiled, even though wcs/fitsfile.c
(which is compiled) depended upon symbols in it. This
resulted in undefined symbols in the libraries, which caused a link
problem when linking against the shared library, e.g.:

/.../libfuntools.so: undefined reference to `getfilesize'